version: "3"

services: 
  api:
    container_name: phones-api
    restart: always
    build: .
    ports: 
      - "3000:3000"
    links:
      - database

  database: 
    container_name: mongodb
    image: mongo
    environment: 
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    volumes: 
      - ./mongo_data:/data/db

    ports:
      - 27017:27017
    # logging:
    #   driver: none
  mongo-seed:
    build: ./mongo-seed
    links:
      - database
